### ISSUE TITLE
can't do a base64_decode of an array

### ISSUE THREAD

**Issue by marrahi8** [ludeus/trusted-timestamps#3]
Hi,

Correct me if I am wrong, but base64_decode only accepts strings, not arrays, therefore the example is not correct, since signRequestfile returns an array.

$signature = TrustedTimestamps::signRequestfile($requestFile, $tsa_url);
file_put_contents($signature_filename, base64_decode($signature));

Sincerely
Toni

**Comment by ludeus** [comment]
yes, missing the ['response_string']
